### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by dzach**
Oops! This is a mistake, please disregard this pull request. I don't know how to delete it.

I am trying to figure out how to use the template for displaying some stl files but I still have troubles with the alternative method.

### CODE REVIEW

**Comment by garyhodgson** [comment]
No worries - give me a shout if I can be of help.  My explanation of the alternative method might not be very clear.

**Comment by dzach** [comment]
Thanks. It's probably me not getting it right with git. I'll create a test repository and try it again. In the meanwhile I have another issue which I'll submit separately.

**Comment by dzach** [comment]
I tried with another test project and I can't get it to work with the alternative method.
After installing jekyll I can run it locally without a problem, but not the pushed to GitHub version. Reading the GitHub help, it seems that the _source: template_ setting is [overridden  by GitHub](https://help.github.com/articles/pages-don-t-build-unable-to-run-jekyll) (last paragraph)

**Comment by garyhodgson** [comment]
Ah, that's embarrassing.  I added the alternative approach at the last minute and I had thought I had tested it deployed to github, but obviously I hadn't, and as you rightly point out it seems the source option is not available when deployed - annoying!

I'll update the readme and blog post to reflect this and will see if there is a fix because I think having a shared template as a submodule is quite useful.

Thanks for finding the bug, and sorry for not having tested it as deployed.

**Comment by dzach** [comment]
Not at all, that's what open source is all about, isn't it? :-) I think this a excellent idea and implementation that adds value to GitHub.

Obviously GitHub wants user pages to be served from the gh-pages branch so that's probably why it overrides the _source_ setting. Maybe the GitHub developers can be persuaded to accept a user defined _source_ setting if it points to an existing submodule in a project.

Some kind of automatic template generation, similar to GitHub's Automatic Page Generator, could of course make the process more straight forward.

**Pull request closed without merging**
